In [1]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
# pyright: ignore[reportMissingModuleSource]
# df = pd.DataFrame({
#     "Name":["amir","ram","raj","harry"],
#     "Age":[34,56,56,23],
#     "Salary":[150000,1022,20000,153000]
# })
# print(df) 
# df = df.dropna()
# df["Age"].fillna(df["Age"].mean(),inplace=True)
# df["Salary"].fillna(df["Salary"].mean(),inplace=True)
# df = df["Age"].astype(float)
# print(df)

df = pd.read_csv("sample_data.csv",encoding="latin1")
df
# df = pd.DataFrame({
#     "Name":["amir","ram","raj","harry"],
#     "C_1":[True,False,True,False],
#     "C_2":[False,True,True,False],
#     "C_3":[True,False,False,True],

# })
# df[["C_1","C_2","C_3"]] = df[["C_1","C_2","C_3"]].astype(int)
# print(df)

      Name  Gender       City Passed
0     Aman    Male      Delhi    Yes
1    Priya  Female     Mumbai    Yes
2    Rahul    Male  Bangalore     No
3   Anjali  Female     Mumbai    Yes
4     Ravi    Male      Delhi    Yes
5    Meera  Female    Chennai     No
6    Arjun    Male  Bangalore    Yes
7     Neha  Female      Delhi    Yes
8    Imran    Male    Chennai     No
9    Sneha  Female     Mumbai    Yes
10     Raj    Male    Chennai    Yes
11   Divya  Female      Delhi     No
12   Kabir    Male     Mumbai    Yes
13  Simran  Female  Bangalore    Yes
14   Karan    Male      Delhi     No
15   Pooja  Female     Mumbai    Yes
16  Rakesh    Male    Chennai    Yes
17    Isha  Female      Delhi     No
18   Rohit    Male      Delhi    Yes
19   Deepa  Female  Bangalore    Yes

In [3]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd

df = pd.read_csv("sample_data.csv",encoding="latin1")
df_L = df.copy()
le = LabelEncoder()
df_L["Gender_Encoder"] = le.fit_transform(df_L["Gender"])
df_L["Passed_Encoder"] = le.fit_transform(df_L["Passed"])
df_Encoder = pd.get_dummies(df_L,columns=["City"])
df_Encoder[["City_Bangalore","City_Chennai","City_Delhi","City_Mumbai"]] = df_Encoder[["City_Bangalore","City_Chennai","City_Delhi","City_Mumbai"]].astype(int)
df_Encoder.drop(columns=["Gender","Passed"],inplace=True)
df_Encoder.head(15)
# print(df_Encoder.to_csv("ML.csv"))

,Name,Gender_Encoder,Passed_Encoder,City_Bangalore,City_Chennai,City_Delhi,City_Mumbai
0,Aman,1,1,0,0,1,0
1,Priya,0,1,0,0,0,1
2,Rahul,1,0,1,0,0,0
3,Anjali,0,1,0,0,0,1
4,Ravi,1,1,0,0,1,0
5,Meera,0,0,0,1,0,0
6,Arjun,1,1,1,0,0,0
7,Neha,0,1,0,0,1,0
8,Imran,1,0,0,1,0,0
9,Sneha,0,1,0,0,0,1
10,Raj,1,1,0,1,0,0
11,Divya,0,0,0,0,1,0
12,Kabir,1,1,0,0,0,1
13,Simran,0,1,1,0,0,0
14,Karan,1,0,0,0,1,0

In [4]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

Uy = [1,1,0,1,1,1,0,0]
Py = [1,0,0,1,1,0,0,1]

print(f"accuracy_score : {accuracy_score(Uy,Py)}")
print(f"precision_score : {precision_score(Uy,Py)}")
print(f"recall_score : {recall_score(Uy,Py)}")
print(f"f1_score : {f1_score(Uy,Py)}")

accuracy_score : 0.625
precision_score : 0.75
recall_score : 0.6
f1_score : 0.6666666666666666

In [1]:
from sklearn.model_selection import train_test_split
import pandas as pd
df = pd.DataFrame({
    "Name":["amir","anam","harry","raj","ram"],
    "Age":[20,30,25,54,32],
    "Salary":[20000,30000,25000,54000,3200]
})
X = df["Age"]
y = df["Salary"]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
print("Training X")
print(X_train)
print("Training y")
print(y_train)
print("Test X")
print(X_test)
print("Test y")
print(y_test)

Training X
4    32
2    25
0    20
3    54
Name: Age, dtype: int64
Training y
4     3200
2    25000
0    20000
3    54000
Name: Salary, dtype: int64
Test X
1    30
Name: Age, dtype: int64
Test y
1    30000
Name: Salary, dtype: int64

In [6]:
from sklearn.preprocessing import StandardScaler
import pandas as pd
Scaler = StandardScaler()
df = pd.DataFrame({
    "Name":["amir","anam","harry","raj","ram"],
    "Age":[20,30,25,54,32],
    "Salary":[20000,30000,25000,54000,3200]
})
df[["Age","Salary"]] = Scaler.fit_transform(df[["Age","Salary"]])
df

    Name       Age    Salary
0   amir -1.045527 -0.391076
1   anam -0.188538  0.216185
2  harry -0.617032 -0.087446
3    raj  1.868236  1.673612
4    ram -0.017140 -1.411275

In [5]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd
Scaler = MinMaxScaler()
df = pd.DataFrame({
    "Name":["amir","anam","harry","raj","ram"],
    "Age":[20,30,25,54,32],
    "Salary":[20000,30000,25000,54000,3200]
})
df[["Age","Salary"]] = Scaler.fit_transform(df[["Age","Salary"]])
df

    Name       Age    Salary
0   amir  0.000000  0.330709
1   anam  0.294118  0.527559
2  harry  0.147059  0.429134
3    raj  1.000000  1.000000
4    ram  0.352941  0.000000

In [1]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
X = [[1],[2],[3],[4],[5]]
y = [40,50,65,75,90]
h = float(input("Enter hours : "))
model.fit(X,y)
pred = model.predict([[h]])[0] 
print(f"{pred}%")

64.0%

In [2]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
X = [[1],[2],[3],[4],[5]]
y = [0,0,1,1,1]
h = float(input("Enter hours : "))
model.fit(X,y)
pred = model.predict([[h]])[0] 
if(pred == 0):
    print("Fall")
else:
    print("Pass")

Pass

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(3)
X = [[100,2],[200,4],[250,4.5],[300,5],[340,6],[360,7]]
y = [0,0,0,1,1,1]
w = float(input("Enter Kg : "))
c = float(input("Enter cm : "))
model.fit(X,y)
pred = model.predict([[w,c]])[0]
if(pred == 0):
    print("apple")
else:
    print("organ")

organ

In [ ]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,confusion_matrix
import numpy as np
Uy = [1,1,0,1,1,1,0,0]
Py = [1,0,0,1,1,0,0,1]
C_M = confusion_matrix(Uy,Py)
print(C_M)
mae = mean_absolute_error(Uy,Py)
mse = mean_squared_error(Uy,Py)
r_mse = np.sqrt(mse)
print(f"MAE : {mae}")
print(f"MSE : {mse}")
print(f"RMSE : {r_mse}")

[[2 1]
 [2 3]]
MAE : 0.375
MSE : 0.375
RMSE : 0.6123724356957945

In [2]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier()
X = [[100,2],[200,4],[300,5],[340,6],[360,7]]
y = [0,0,1,1,1]
w = float(input("Enter cm : "))
c = float(input("Enter color_S : "))
model.fit(X,y)
pred = model.predict([[w,c]])[0] 
if(pred == 0):
    print("apple")
else:
    print("organ")

organ

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.model_selection import train_test_split
import numpy as np


df = pd.read_csv("student.csv")
X = df[["Hours"]]
y = df["Score"]

h = float(input("Enter hours : "))
X_train,X_test,y_train,y_test = train_test_split(X,y)

model = LinearRegression()
model.fit(X_train,y_train)
pred = model.predict(X_test)
mae = mean_absolute_error(pred,y_test)
mse = mean_squared_error(pred,y_test)
r_mse = np.sqrt(mse)
print(f"MAE : {np.round(mae,2)}")
print(f"MSE : {np.round(mse,2)}")
print(f"RMSE : {np.round(r_mse,2)}")

pred_result = model.predict([[h]])[0]
print(f"Hours {np.round(h,2)} : {np.round(pred_result,2)}%")

MAE : 0.86
MSE : 0.92
RMSE : 0.96
Hours 7.0 : 87.14%

C:\Users\Amir sohail\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(